[package]
name = "hexocat-bot"
version = "0.1.0"
authors = ["Araz Abishov <araz.abishov.gsoc@gmail.com>"]

[dependencies]
# easy way to make calls to APIs
anterofit = "0.1.1"

# serialization library
serde = "0.9"
serde_json = "0.9"
serde_derive = "0.9"
